apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: LoadBalancer
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: {{ .Values.registry.externalPort }}
      targetPort: {{ .Values.registry.port }}