apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: {{ .Values.registry.replicaCount }}
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      affinity: {{- toYaml .Values.registry.affinity | nindent 8 }}
      containers:
        - name: registry
          image: "{{ required "Missing required value: registry.image" .Values.registry.image }}:{{ .Values.registry.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.registry.port }}
          readinessProbe:
            httpGet:
              path: /v0/health
              port: {{ .Values.registry.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /v0/health
              port: {{ .Values.registry.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 2
          env:
          {{- toYaml .Values.registry.env | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ required "Missing required value: registry.github_secret_name" .Values.registry.github_secret_name }}
          resources:
            requests:
              cpu: {{ .Values.registry.resources.requests.cpu }}
              memory: {{ .Values.registry.resources.requests.memory }}
            limits:
              cpu: {{ .Values.registry.resources.limits.cpu }}
              memory: {{ .Values.registry.resources.limits.memory }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
