encryptionsalt: v1:/U+EZEOTkg4=:v1:1FsnL1dVn8+ZJhms:EIv82sKNuUj0DFqLTZeR7fPMTXjNIg==
config:
  mcp-registry:environment: local
  mcp-registry:githubClientId: "1"
  mcp-registry:provider: local
  mcp-registry:githubClientSecret:
    secure: v1:4lHYd2bTVCBO0Y2L:vmPKh3CHmcOvjRPNRZKUjv4=
